### ISSUE TITLE
Variable migration doesn't work when variable value is "None"

### ISSUE THREAD

**Issue by pgagnon** [astronomer/starship#33]

**Comment by atulya-astronomer** [comment]
@pgagnon, I tried to reproduce this but wasn't able to. If possible, could you share some more details?

@fritz-astronomer, was this fixed in an earlier release? If yes, I'll close this issue.

**Comment by fritz-astronomer** [comment]
I don't think it was fixed, to my recollection. 
I remember that - some how, the "None" was getting interpreted as false-y. 
Maybe it was under a lower Airflow version? 
I can't find much in OSS Airflow issues / slack, but I could've sworn I brought it up somewhere.

**Comment by atulya-astronomer** [comment]
> Maybe it was under a lower Airflow version? I can't find much in OSS Airflow issues / slack, but I could've sworn I brought it up somewhere.

That could be the case. I tried it on Airflow 2.10 with values `None`, `"None"` (with quotes), `none` and `null`. All seemed to be working fine. Maybe an Airflow bug that's fixed rather than Starship?

**Comment by fritz-astronomer** [comment]
🤷 👍

**Comment by atulya-astronomer** [comment]
😅 

Closing this issue then. Will re-open if it pops up.
