### ISSUE TITLE
Starship Plugin DAG Cutover Tab not working for Google Cloud Composer Airflow 2.4.3 and Airflow 2.5.3

### ISSUE THREAD

**Issue by iamakashladdha** [astronomer/starship#61]
PyPi - 	
`astronomer-starship>=1.2.0`

Starship Plugin is unable to fetch the DAGs for Composer Airflow 2.5.3, Connections/pools/Variables/Environment Variables are available to migrate to Astro
![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/3f2d561c-a102-4577-8be3-cc15bdd606a8/74ab9cbf-3542-44bc-bbb8-e1c0204858bd/Untitled.png)

Starship Plugin is unable to fetch the DAGs for Composer Airflow 2.4.3, Connections/pools/Variables/Environment Variables are available to migrate to Astro
<img width="859" alt="Untitled" src="https://github.com/astronomer/starship/assets/98732616/92b7e723-285c-4e14-9a56-ba541076bed5">

Thus Unable to do DAG Cutover to Astro using Starship Migration Plugin for Google Cloud Composer both the available versions.

Admin access was granted to myself using gcloud CLI and that is how 16 DAGs were visible in Composer Airflow UI and were able to execute them.

Composer Airflow 2.5.3 DAGs
<img width="1716" alt="image" src="https://github.com/astronomer/starship/assets/98732616/f1de8f92-0fa4-4f3f-8383-672a0fa58d78">

Composer Airflow 2.4.3 DAGs
<img width="1719" alt="image" src="https://github.com/astronomer/starship/assets/98732616/dfca54d6-02b1-420e-9780-57ddb2d39404">

**Comment by fritz-astronomer** [comment]
Possible fix in https://github.com/astronomer/starship/pull/63 - testing might be challenging

**Comment by fritz-astronomer** [comment]
Closing as `WONTFIX` - Starship v2 has a full rewrite, which should fix this
