### ISSUE TITLE
Unable to migrate DAG History for the recent DAG runs using Starship Plugin for MWAA Airflow 2.4.3, 2.5.1 and 2.6.3 

### ISSUE THREAD

**Issue by iamakashladdha** [astronomer/starship#62]
Below are the sequence of steps performed in the DAG Cutover Page to validate the DAG History Migration from MWAA Airflow to Astro Airflow

Impacted - MWAA Airflow 2.4.3, 2.5.1 and 2.6.3

DAG Pause/Unpause is working as expected using the Starship Plugin DAG Cutover Page

Prior to cutover - DAG cutover page is populated as expected, Local being MWAA deployment while Remote being Astro Deployment.

- Few DAGs running in MWAA
- Nothing running in Astro, only fresh Deployment of DAGs
        
<img width="1707" alt="Untitled (1)" src="https://github.com/astronomer/starship/assets/98732616/85c80916-08b3-4d06-85b1-d7575b6408b0">

- Thereafter all the DAGs paused on MWAA before migrating the DAG run History
    
<img width="1712" alt="Untitled (2)" src="https://github.com/astronomer/starship/assets/98732616/0c5a5a66-9260-4265-89e4-76d00ffc24b0">
    
- **DAG run History**, Clicked to migrate the DAG run history, but it hasn’t been migrated yet
       
<img width="1700" alt="Untitled (4)" src="https://github.com/astronomer/starship/assets/98732616/77663139-8189-49a7-9ad3-6eb99cb46121">
 
- Waited for 5+ mins on Astro UI, but no History Yet.
        
<img width="1724" alt="Untitled (5)" src="https://github.com/astronomer/starship/assets/98732616/4071effa-7357-446b-bb29-27c316411109">

- Check Mark against the Migrate Dag History is shown, but the DAG History didn’t get migrated
    
<img width="1696" alt="Untitled (6)" src="https://github.com/astronomer/starship/assets/98732616/945cc2d0-03ec-415a-87ba-28d122c124e9">

- Astro
    
<img width="1711" alt="Untitled (7)" src="https://github.com/astronomer/starship/assets/98732616/1d264a42-0297-43e3-b365-bdc9cb61eafa">

- No DAG History in DAG Run list as well, All DAG runs are after 8:35 AM UTC on 19th Oct https://clkvh3b46003m01kbalgwwdcy.astronomer.run/d9n6jgc3/dagrun/list/
    
<img width="1702" alt="Untitled (8)" src="https://github.com/astronomer/starship/assets/98732616/519289e4-ebb3-4f72-aa56-0460625b117e">
    
- Unpausing the DAG on Remote i.e. Astro - Did unpause on Astro using the DAG cutover tab and DAGs started executing on Astro as expected.
    
<img width="1688" alt="Untitled (10)" src="https://github.com/astronomer/starship/assets/98732616/1557e0d4-2944-4178-b5cd-ffe3c49fc3ef">

- DAG execution on Astro using Starship Migration Plugin (but no History)
    
<img width="1720" alt="Untitled (9)" src="https://github.com/astronomer/starship/assets/98732616/813737b2-a067-440c-92d5-f788b9ed3c8a">

**Comment by fritz-astronomer** [comment]
Looks like starship is unavailable on the target Airflow? 
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://clkvh3b46003m01kbalgwwdcy.astronomer.run/du5kr2ay/starship/dag_history/receive
```
DAG History Migration only works if starship can talk to itself

**Comment by fritz-astronomer** [comment]
Adding here, as well

Starship Task History Migration Not Working RT8.8 -> 8.8#52
(private slack history)
https://astronomer.slack.com/archives/C03TZ44G75M/p1692217227951499

**Comment by fritz-astronomer** [comment]
Closing as `WONTFIX` - Starship v2 has a full rewrite, which should fix this
