### ISSUE TITLE
Software Support

### ISSUE THREAD

**Issue by fritz-astronomer** [astronomer/starship#68]
Starship should support a software installation as a destination, not just hybrid/hosted

**Comment by fritz-astronomer** [comment]
@nsAstro Starship can be installed to any Airflow already 👍

**Comment by rwalshe** [comment]
@fritz-astronomer 

Wanted to be certain on this

- SoftwareA-AirflowX migration to SoftwareB-AirflowY

requires the changes being implemented in Starship2.  The above is not a supported migration path with Starship1.  The Software destination is the delta between Starship1 and 2 functionality.  The Software source is supported by Starship1, for example Software->Astro migrations are supported in Starship1.  

Is that correct?

**Comment by fritz-astronomer** [comment]
> for example Software->Astro migrations are supported in Starship1
👍 
> SoftwareA-AirflowX migration to SoftwareB-AirflowY requires the changes being implemented in Starship2
👍
