### ISSUE TITLE
Starship not able to connect to source Airflow deployment on Astro. 

### ISSUE THREAD

**Issue by ben-astro** [astronomer/starship#73]
On a migration call with Entrata (Hybrid->Hosted), we attempted to use Starship to move configs over. 

Customer successfully added `astronomer-starship` to their `requirements.txt` file and deployed to both source and target Airflows on Astro, both of which are on Runtime 8.8.0. 

In the source Airflow, after adding Astro token and selecting the target Airflow in Migration Utility plugin page, the page sat at "loading" and wouldn't pull any data (no Connections, no Vars, no Env Vars, etc. 
![image](https://github.com/astronomer/starship/assets/68117952/7582811e-c9e2-49bf-9a1c-9a6b9e4e062c)

In browser troubleshooting, we were receiving 504 Gateway Timeout errors: 
`https://entrata.astronomer.run/d9enw5p7/starship/tabs/connections 504 (Gateway Timeout)`. I validated that the shortDeploymentID in this case was the source Airflow (`Data Platform`). The Target Airflow is `Data Platform - Hosted`. 
![image](https://github.com/astronomer/starship/assets/68117952/832e50b5-6fd6-4ab6-a8e1-570359b5e22a)

One issue which _could_ be related, not sure, is that Entrata's Org type was `Hybrid` (they've switched it back and forth during their Manual Migration, as folks needed to make changes to previous Hybrid deployments, during the time in which they've taken to stand up new Hosted deployments). I switched it to `Hosted` during the call and tried Starship again, but no luck. 

Also had Entrata log out of Starship and log back in, but no change either.

**Comment by fritz-astronomer** [comment]
WONTFIX - Starship v2 is released and this may no longer apply
