### ISSUE TITLE
Starship should mask environment vars, as they may contain secret values

### ISSUE THREAD

**Issue by ben-astro** [astronomer/starship#93]
**Original Title**:
Starship doesn't respect `secret` mask when migrating ENV VARs in Astro

**Source**: Astro - Hybrid
**Destination**: Astro - Hosted (Manual Migration)
**Airflow Version**: Runtime 8.8.0
**Starship Version**: 2.0.0

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version - unsure
**Screenshots**
<img width="1034" alt="image" src="https://github.com/astronomer/starship/assets/68117952/b976be56-bd3a-41b8-9b58-778a76ef4af6">
Shows ^^ Astro env vars marked as secret. When viewing in Starship Env Vars tab, it is plaintext. Not including screenshot for sensitivity. 

**Logs**
N/A

**Additional context**
N/A

**Comment by ben-astro** [comment]
After discussion with @fritz-astronomer, seems like Starship is operating as designed. It doesn't leverage the secret-masking UI features in Astro; just prints out what has been written to Airflow's env. Recommend removing values from the Env Vars tab or hiding them by default (with a checkbox to reveal, perhaps).

**Comment by fritz-astronomer** [comment]
Yea, to include part of our discussion here - Starship talks to Airflow, not Astro - and only Astro knows which env vars were marked "Secret". Starship wouldn't be able to talk to Astro, in circumstances that the source is OSS, MWAA, etc.

It can maybe mask all env vars. Airflow also has some "secret-ish" logic, that could maybe be used?
