### ISSUE TITLE
New TI field in 2.8 - custom_operator_name

### ISSUE THREAD

**Issue by fritz-astronomer** [astronomer/starship#98]
```
custom_operator_name = Column(String(1000))
```

**Comment by atulya-astronomer** [comment]
Tested using Pytest, Astro <> Astro and MWAA <> Astro for Airflow 3.10. All test cases passed and didn't run into any issues while manual testing. Merging the associated PR to main. A release has already been created on `PyPI`. Attached MWAA starship page post migration for reference.
